#!/bin/bash
# GUÍA RÁPIDA DE INICIO - PLANIFY

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                   PLANIFY - GUÍA RÁPIDA ⚡                     ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "🎯 PASO 1: Ir a la carpeta de la app"
echo "───────────────────────────────────────"
echo "cd cypress/e2e/Pruebas-Planify/app"
echo ""
echo "📦 PASO 2: Instalar dependencias"
echo "───────────────────────────────────────"
echo "npm install"
echo ""
echo "🚀 PASO 3: Ejecutar la aplicación"
echo "───────────────────────────────────────"
echo "npm run dev"
echo "→ Se abrirá en: http://localhost:5173"
echo ""
echo "🧪 PASO 4: Ejecutar tests de Cypress"
echo "───────────────────────────────────────"
echo "npx cypress open"
echo "→ Selecciona: 'Pruebas Planify.cy.js'"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📁 ARCHIVOS IMPORTANTES:"
echo ""
echo "1. api.js"
echo "   └─ Servicio de API Mock (sin backend real)"
echo ""
echo "2. database.js"
echo "   └─ Almacenamiento local con IndexedDB"
echo ""
echo "3. types.js"
echo "   └─ Constantes de roles y permisos"
echo ""
echo "4. README_JAVASCRIPT.md"
echo "   └─ Documentación completa"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✨ CARACTERÍSTICAS:"
echo "───────────────────────────────────────"
echo "✅ Sin backend real (usa IndexedDB)"
echo "✅ Código 100% JavaScript"
echo "✅ Almacenamiento persistente"
echo "✅ Tests listos para ejecutar"
echo ""
